// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJRMFiHbuMD_XHQrEZK13FOiQmeGKLWxo',
    appId: '1:57209906652:web:af48fa4e86b016a0811b19',
    messagingSenderId: '57209906652',
    projectId: 'gotoapp-357309',
    authDomain: 'gotoapp-357309.firebaseapp.com',
    databaseURL: 'https://gotoapp-357309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotoapp-357309.appspot.com',
    measurementId: 'G-2P2ZX14SRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHD7F-WwaqChoZaeYh6dxuXfhb6WeNZLM',
    appId: '1:57209906652:android:bf2cb05cacb4749a811b19',
    messagingSenderId: '57209906652',
    projectId: 'gotoapp-357309',
    databaseURL: 'https://gotoapp-357309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotoapp-357309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5KfblxjaX197l_WjioyTHZNCb2w5WDkI',
    appId: '1:57209906652:ios:a9a91227bff0dd5d811b19',
    messagingSenderId: '57209906652',
    projectId: 'gotoapp-357309',
    databaseURL: 'https://gotoapp-357309-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gotoapp-357309.appspot.com',
    iosClientId: '57209906652-lq65tgbmnpe1sulepakoctbc193hgbpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.goTo',
  );
}
